WARNING_FLAGS="-Werror=odr -Werror=strict-aliasing"

COMMON_FLAGS="-march=raptorlake -O2 -pipe -flto=thin ${WARNING_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS}"

CC="clang"
CXX="clang++"
CPP="clang-cpp"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=raptorlake -Clinker-plugin-lto"

MAKEOPTS="-j16 -l18"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"

FEATURES="${FEATURES} candy ccache parallel-fetch parallel-install -ebuild-locks -merge-wait"

EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y"

# Optionally, to use custom signing keys.
MODULES_SIGN_KEY="/home/yoimiya/dotfiles/gentoo-openrc-hyprland/kernel_key.pem"
MODULES_SIGN_CERT="/home/yoimiya/dotfiles/gentoo-openrc-hyprland/kernel_key.pem" # Only required if the MODULES_SIGN_KEY does not also contain the certificate.
MODULES_SIGN_HASH="sha512" # Defaults to sha512.

# Optionally, to boot with secureboot enabled, may be the same or different signing key.
SECUREBOOT_SIGN_KEY="/home/yoimiya/dotfiles/gentoo-openrc-hyprland/kernel_key.pem"
SECUREBOOT_SIGN_CERT="/home/yoimiya/dotfiles/gentoo-openrc-hyprland/kernel_key.pem"

LC_MESSAGES=C.UTF-8

