# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

CC="clang"
CPP="clang-cpp" # necessary for xorg-server and possibly other packages
CXX="clang++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

MAKEOPTS="-j16 -l18"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"

FEATURES="${FEATURES} candy ccache binpkg-request-signature getbinpkg parallel-fetch parallel-install -ebuild-locks -merge-wait"

GENTOO_MIRRORS="https://mirrors.zju.edu.cn/gentoo"

# emerge
# EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y --jobs=8 --load-average=10"
EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y"

# USE

# Fuck you qtwebengine
USE="${USE} -webengine"

# NVIDIA
USE="${USE} cuda nvenc"

# Media
USE="${USE} ffmpeg vaapi"

# Kernel
USE="${USE} dist-kernel"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
