kernel_cmdline="root=UUID=e41870ae-a9db-4854-b27a-9475ad6aa7b1 rootfstype=xfs rootflags=rw,relatime nvidia-drm.modeset=1 nvidia-drm.fbdev=1 zswap.enabled=1 zswap.compressor=zstd i915.force_probe=!a7a0 xe.force_probe=a7a0"
uefi="yes"
add_dracutmodules+=" plymouth "
