add_dracutmodules+=" plymouth resume "
force_drivers+=" xe i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm "
kernel_cmdline="root=UUID=e41870ae-a9db-4854-b27a-9475ad6aa7b1 rootfstype=xfs rootflags=rw,relatime quiet splash nvidia-drm.modeset=1 nvidia-drm.fbdev=1 zswap.enabled=1 zswap.compressor=zstd i915.force_probe=!a7a0 xe.force_probe=a7a0 mem_sleep_default=s2idle nowatchdog hibernate.compressor=lz4 resume=UUID=e41870ae-a9db-4854-b27a-9475ad6aa7b1 resume_offset=8812930"
uefi="yes"
