COMMON_FLAGS="-march=native -O3 -pipe -flto=thin -Werror=odr -Werror=strict-aliasing"
# COMMON_FLAGS="-march=native -O3 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native -Clinker-plugin-lto"

CC="clang"
CPP="clang-cpp" # necessary for xorg-server and possibly other packages
CXX="clang++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
LD="ld.lld"

MAKEOPTS="-j16 -l18"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

FEATURES="${FEATURES} candy ccache binpkg-request-signature getbinpkg parallel-fetch parallel-install -ebuild-locks -merge-wait"

# GENTOO_MIRRORS="https://mirrors.zju.edu.cn/gentoo"
# GENTOO_MIRRORS="https://mirrors.ustc.edu.cn/gentoo"

EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y"

LC_MESSAGES=C.UTF-8
