#! /bin/bash

export QT_QPA_PLATFORMTHEME=qt6ct
export XMODIFIERS=@im=fcitx
# export WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1
# export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
# export WLR_DRM_DEVICES=/dev/dri/card0

dbus-run-session sway --unsupported-gpu
# dbus-run-session sway
