COMMON_FLAGS="-march=raptorlake -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"

CC="clang"
CXX="clang++"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=raptorlake"

MAKEOPTS="-j12 -l16"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

FEATURES="${FEATURES} candy ccache binpkg-request-signature getbinpkg parallel-fetch parallel-install -ebuild-locks -merge-wait"

# GENTOO_MIRRORS="https://mirrors.zju.edu.cn/gentoo"
# GENTOO_MIRRORS="https://mirrors.ustc.edu.cn/gentoo"

EMERGE_DEFAULT_OPTS="--keep-going --with-bdeps=y"

LC_MESSAGES=C.UTF-8
